"""empty message

Revision ID: 091fa04f8d40
Revises: aca5219e9f87
Create Date: 2020-08-26 18:05:12.801430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '091fa04f8d40'
down_revision = 'aca5219e9f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('uid', sa.Integer(), nullable=False))
    op.add_column('article', sa.Column('updated', sa.DateTime(), nullable=False))
    op.alter_column('article', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_article_uid'), 'article', ['uid'], unique=False)
    op.drop_column('article', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title', mysql.VARCHAR(length=30), nullable=False))
    op.drop_index(op.f('ix_article_uid'), table_name='article')
    op.alter_column('article', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('article', 'updated')
    op.drop_column('article', 'uid')
    # ### end Alembic commands ###
