"""empty message

Revision ID: 1c5aacc8f88e
Revises: 91f9a9885bd5
Create Date: 2020-08-25 19:13:13.894224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5aacc8f88e'
down_revision = '91f9a9885bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('gender', sa.Enum('male', 'female', 'unknow'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.drop_column('user', 'created')
    op.drop_column('user', 'city')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
