"""empty message

Revision ID: 64bf113463e8
Revises: f695342de6b4
Create Date: 2020-08-27 10:06:21.710284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bf113463e8'
down_revision = 'f695342de6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('cid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'cid')
    # ### end Alembic commands ###
