"""empty message

Revision ID: 7d6a7b150607
Revises: 1fcb25b4b61d
Create Date: 2020-08-28 19:25:59.918054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6a7b150607'
down_revision = '1fcb25b4b61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'fid')
    )
    op.add_column('user', sa.Column('n_fans', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('n_follow', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'n_follow')
    op.drop_column('user', 'n_fans')
    op.drop_table('follow')
    # ### end Alembic commands ###
