"""empty message

Revision ID: a1bd703a171d
Revises: 7d6a7b150607
Create Date: 2020-08-28 19:45:28.697528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bd703a171d'
down_revision = '7d6a7b150607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumb',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'aid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumb')
    # ### end Alembic commands ###
