"""empty message

Revision ID: dca9b31941a3
Revises: 64bf113463e8
Create Date: 2020-08-27 21:58:38.801371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca9b31941a3'
down_revision = '64bf113463e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumb',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_thumb_aid'), 'thumb', ['aid'], unique=False)
    op.create_index(op.f('ix_thumb_uid'), 'thumb', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumb_uid'), table_name='thumb')
    op.drop_index(op.f('ix_thumb_aid'), table_name='thumb')
    op.drop_table('thumb')
    # ### end Alembic commands ###
